#!/usr/bin/env bash

if [ #? -ne 4 ]
then
  echo -e "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
else
  echo -e "Connecting .......  \n"
fi

PATH_2_FILE="$1"
IP="$2"
USERNAME="$3"
PATH_2_SSH_KEY="$4"

Remote_host="$USERNAME@$IP"
local_host="$USERNAME@$HOSTNAME"

# Test connectivity to remote location
scp -q ${Remote_host}:~/ /dev/null

if [ $? -eq 0 ]; then

# Secure copy to remote location using scp
	scp ${Local_host}:${PATH_2_FILE} ${IP}:~/
	echo -e "Copying in progress....\n ...... \n .....\n"
	sleep 1
	echo -e "Schema Copied to $Remote_location \n"
else
	echo -e  "\nRemote location not reachable, check your connection/IP"
fi
