#!/usr/bin/env bash
# Transfers a file from local host to remote host

if [ $# -ne 4 ]; then
  echo -e "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
else
  echo -e "Connecting .......  \n"
fi

PATH_2_FILE="$1"
IP="$2"
USERNAME="$3"
PATH_2_SSH_KEY="$4"

Remote_host="$USERNAME@$IP"

# Restrict ssh-key permission
chmod 600 ${PATH_2_SSH_KEY}

# Test connectivity to remote location
#scp -i ${PATH_2_SSH_KEY} -q ${Remote_host}:~/.bashrc /dev/null

if [ $? -eq 0 ]; then
# Secure copy to remote location using scp
  scp -i ${PATH_2_SSH_KEY} -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r  ${PATH_2_FILE} ${Remote_host}:~/
  echo -e "Copying in progress....\n ...... \n .....\n"
  sleep 1
  echo -e "File Copied to $Remote_host \n"
else
  echo -e  "\nRemote location not reachable, check your connection/IP"
fi
